services:
  app:
    env_file: .env
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
    depends_on:
      db:
        condition: service_healthy

  task:
    image: ghcr.io/evanston09/forks:main
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
    healthcheck:
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: forks
      POSTGRES_PASSWORD: forkspass
      POSTGRES_DB: forks
    volumes:
      - ./storage/docker/psql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forks -d forks"]
      interval: 5s
      timeout: 5s
      retries: 5
