/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Model from Hoang Vu
*/

import { useGLTF } from '@react-three/drei';
import type { ThreeElements } from '@react-three/fiber';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

type DoorProps = ThreeElements['group'] & { opacity?: number };

type GLTFResult = GLTF & {
    nodes: {
        Cube001: THREE.Mesh;
    };
    materials: {
        ['Material.003']: THREE.MeshStandardMaterial;
    };
};

export default function Door({ opacity = 1, ...props }: DoorProps) {
    const { nodes, materials } = useGLTF(
        '/ncssm_door.glb',
    ) as unknown as GLTFResult;

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials['Material.003']}
                material-opacity={opacity}
                material-transparent
            />
        </group>
    );
}

useGLTF.preload('/ncssm_door.glb');
