name: Deploy release

on:
  workflow_dispatch:

jobs:
  deploy-release:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy new images to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd ~/services && docker compose down forks forks_task && docker compose pull forks && docker compose up -d
