name: Deploy release

on:
  workflow_run:
    workflows: ['Build Docker image']
    types: [completed]

jobs:
  deploy-release:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy new images to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd ~/services && docker compose down forks forks_tasks && docker compose pull forks && docker compose up -d